### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wwhgtt** [SpencerCDixon/react-testing-starter-kit#5]
PhantomJS如果没有事先全局安装过的话会报错的

**Comment by wwhgtt** [comment]
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/tp/0x6f36f568vfpdz31m475fyc0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
|
Error making request.
Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TLSWrap.onread (net.js:552:26)

Please report this full log at https://github.com/Medium/phantomjs
^Z
